name: Build and Release

on:
  push:
    tags:
      - 'v*'   # запускается при пуше любого тега, начинающегося с 'v'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write   # даёт право создавать релиз
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
            arch: x64
          - os: macos-latest
            platform: mac
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build-win/mac/linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.zip
            dist/*.dmg.blockmap
            dist/*.exe.blockmap
            dist/latest-linux.yml
            dist/latest-mac.yml
            dist/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}